-- Schema of the database for predicting NHL contact values and doing some data visualization
-- Version 0.1, debug mode

-- Drop all already defined tables
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS cities;
DROP TABLE IF EXISTS team_season_stats;
DROP TABLE IF EXISTS skater_season_stats;
DROP TABLE IF EXISTS goalie_season_stats;

-- Table for cities for map visualizations
CREATE TABLE cities
(
    name_NHL_API TEXT PRIMARY KEY NOT NULL,
    name_local TEXT NOT NULL,
    name_english TEXT NOT NULL,
    country TEXT,
    state TEXT,
    state_code CHAR(2),
    longitude REAL,
    latitude REAL
);

-- Table for players. Currently only has information needed to make the map visualization
-- In the final version, player should not be associated with a team. This association should come through statistics table that is specific for a season, since a player can change teams. Keep it here for initial testing before statistics tables are implemented.
CREATE TABLE players
(
    id INTEGER PRIMARY KEY NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    birth_city TEXT NOT NULL,
    birth_date DATE,
    position CHAR(1),
    handedness CHAR(1),
    headshot TEXT,
    height INTEGER,
    weight INTEGER,
    FOREIGN KEY (birth_city) REFERENCES cities(name_NHL_API)
);

-- Table for teams on NHL
-- Currently the latest arena is listed in the teams table
-- If the project is ever expanded to contain past arenas for teams, the arenas need to go to their own table
-- We might want to also use franchise_id if the project is expanded to historical teams
CREATE TABLE teams
(
    code CHAR(3) PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    city TEXT NOT NULL,
    logo TEXT,
    arena TEXT,
    arena_capacity INTEGER,
    arena_latitude REAL,
    arena_longitude REAL,
    FOREIGN KEY (city) REFERENCES cities(name_NHL_API)
);

-- Statistics tables are filled directly from MoneyPuck csv files
-- See the MoneyPuck dictionary for explanation of column values
-- TODO: Team stats are missing the number of wins. Need to get this from NHL API instead of MoneyPuck
CREATE TABLE team_season_stats
(
    id INTEGER PRIMARY KEY NOT NULL,
    team CHAR(3) NOT NULL,
    season INTEGER NOT NULL,
    situation TEXT NOT NULL CHECK (situation IN ('other', 'all', '5on5', '5on4', '4on5')),
    phase TEXT NOT NULL CHECK (phase IN ('regular', 'playoffs')),
    games_played INTEGER,
    xGoalsPercentage REAL,
    corsiPercentage REAL,
    fenwickPercentage REAL,
    icetime INTEGER,
    xOnGoalFor REAL,
    xGoalsFor REAL,
    xReboundsFor REAL,
    xFreezeFor REAL,
    xPlayStoppedFor REAL,
    xPlayContinuedInZoneFor REAL,
    xPlayContinuedOutsideZoneFor REAL,
    flurryAdjustedxGoalsFor REAL,
    scoreVenueAdjustedxGoalsFor REAL,
    flurryScoreVenueAdjustedxGoalsFor REAL,
    shotsOnGoalFor INTEGER,
    missedShotsFor INTEGER,
    blockedShotAttemptsFor INTEGER,
    shotAttemptsFor INTEGER,
    goalsFor INTEGER,
    reboundsFor INTEGER,
    reboundGoalsFor INTEGER,
    freezeFor INTEGER,
    playStoppedFor INTEGER,
    playContinuedInZoneFor INTEGER,
    playContinuedOutsideZoneFor INTEGER,
    savedShotsOnGoalFor INTEGER,
    savedUnblockedShotAttemptsFor INTEGER,
    penaltiesFor INTEGER,
    penaltyMinutesFor INTEGER,
    faceOffsWonFor INTEGER,
    hitsFor INTEGER,
    takeawaysFor INTEGER,
    giveawaysFor INTEGER,
    lowDangerShotsFor INTEGER,
    mediumDangerShotsFor INTEGER,
    highDangerShotsFor INTEGER,
    lowDangerxGoalsFor REAL,
    mediumDangerxGoalsFor REAL,
    highDangerxGoalsFor REAL,
    lowDangerGoalsFor INTEGER,
    mediumDangerGoalsFor INTEGER,
    highDangerGoalsFor INTEGER,
    scoreAdjustedShotsAttemptsFor REAL,
    unblockedShotAttemptsFor INTEGER,
    scoreAdjustedUnblockedShotAttemptsFor REAL,
    dZoneGiveawaysFor INTEGER,
    xGoalsFromxReboundsOfShotsFor REAL,
    xGoalsFromActualReboundsOfShotsFor REAL,
    reboundxGoalsFor REAL,
    totalShotCreditFor REAL,
    scoreAdjustedTotalShotCreditFor REAL,
    scoreFlurryAdjustedTotalShotCreditFor REAL,
    xOnGoalAgainst REAL,
    xGoalsAgainst REAL,
    xReboundsAgainst REAL,
    xFreezeAgainst REAL,
    xPlayStoppedAgainst REAL,
    xPlayContinuedInZoneAgainst REAL,
    xPlayContinuedOutsideZoneAgainst REAL,
    flurryAdjustedxGoalsAgainst REAL,
    scoreVenueAdjustedxGoalsAgainst REAL,
    flurryScoreVenueAdjustedxGoalsAgainst REAL,
    shotsOnGoalAgainst INTEGER,
    missedShotsAgainst INTEGER,
    blockedShotAttemptsAgainst INTEGER,
    shotAttemptsAgainst INTEGER,
    goalsAgainst INTEGER,
    reboundsAgainst INTEGER,
    reboundGoalsAgainst INTEGER,
    freezeAgainst INTEGER,
    playStoppedAgainst INTEGER,
    playContinuedInZoneAgainst INTEGER,
    playContinuedOutsideZoneAgainst INTEGER,
    savedShotsOnGoalAgainst INTEGER,
    savedUnblockedShotAttemptsAgainst INTEGER,
    penaltiesAgainst INTEGER,
    penaltyMinutesAgainst INTEGER,
    faceOffsWonAgainst INTEGER,
    hitsAgainst INTEGER,
    takeawaysAgainst INTEGER,
    giveawaysAgainst INTEGER,
    lowDangerShotsAgainst INTEGER,
    mediumDangerShotsAgainst INTEGER,
    highDangerShotsAgainst INTEGER,
    lowDangerxGoalsAgainst REAL,
    mediumDangerxGoalsAgainst REAL,
    highDangerxGoalsAgainst REAL,
    lowDangerGoalsAgainst INTEGER,
    mediumDangerGoalsAgainst INTEGER,
    highDangerGoalsAgainst INTEGER,
    scoreAdjustedShotsAttemptsAgainst REAL,
    unblockedShotAttemptsAgainst INTEGER,
    scoreAdjustedUnblockedShotAttemptsAgainst REAL,
    dZoneGiveawaysAgainst INTEGER,
    xGoalsFromxReboundsOfShotsAgainst REAL,
    xGoalsFromActualReboundsOfShotsAgainst REAL,
    reboundxGoalsAgainst REAL,
    totalShotCreditAgainst REAL,
    scoreAdjustedTotalShotCreditAgainst REAL,
    scoreFlurryAdjustedTotalShotCreditAgainst REAL,
    FOREIGN KEY (team) REFERENCES teams(code)
);

-- Statistics tables are filled directly from MoneyPuck csv files
-- See the MoneyPuck dictionary for explanation of column values
CREATE TABLE skater_season_stats
(
    id INTEGER PRIMARY KEY NOT NULL,
    playerId INTEGER NOT NULL,
    season INTEGER NOT NULL,
    team CHAR(3) NOT NULL,
    situation TEXT NOT NULL CHECK (situation IN ('other', 'all', '5on5', '5on4', '4on5')),
    phase TEXT NOT NULL CHECK (phase IN ('regular', 'playoffs')),
    games_played INTEGER,
    icetime INTEGER,
    shifts INTEGER,
    gameScore REAL,
    onIce_xGoalsPercentage REAL,
    offIce_xGoalsPercentage REAL,
    onIce_corsiPercentage REAL,
    offIce_corsiPercentage REAL,
    onIce_fenwickPercentage REAL,
    offIce_fenwickPercentage REAL,
    iceTimeRank INTEGER,
    I_F_xOnGoal REAL,
    I_F_xGoals REAL,
    I_F_xRebounds REAL,
    I_F_xFreeze REAL,
    I_F_xPlayStopped REAL,
    I_F_xPlayContinuedInZone REAL,
    I_F_xPlayContinuedOutsideZone REAL,
    I_F_flurryAdjustedxGoals REAL,
    I_F_scoreVenueAdjustedxGoals REAL,
    I_F_flurryScoreVenueAdjustedxGoals REAL,
    I_F_primaryAssists INTEGER,
    I_F_secondaryAssists INTEGER,
    I_F_shotsOnGoal INTEGER,
    I_F_missedShots INTEGER,
    I_F_blockedShotAttempts INTEGER,
    I_F_shotAttempts INTEGER,
    I_F_points INTEGER,
    I_F_goals INTEGER,
    I_F_rebounds INTEGER,
    I_F_reboundGoals INTEGER,
    I_F_freeze INTEGER,
    I_F_playStopped INTEGER,
    I_F_playContinuedInZone INTEGER,
    I_F_playContinuedOutsideZone INTEGER,
    I_F_savedShotsOnGoal INTEGER,
    I_F_savedUnblockedShotAttempts INTEGER,
    penalties INTEGER,
    I_F_faceOffsWon INTEGER,
    I_F_hits INTEGER,
    I_F_takeaways INTEGER,
    I_F_giveaways INTEGER,
    I_F_lowDangerShots INTEGER,
    I_F_mediumDangerShots INTEGER,
    I_F_highDangerShots INTEGER,
    I_F_lowDangerxGoals REAL,
    I_F_mediumDangerxGoals REAL,
    I_F_highDangerxGoals REAL,
    I_F_lowDangerGoals INTEGER,
    I_F_mediumDangerGoals INTEGER,
    I_F_highDangerGoals INTEGER,
    I_F_scoreAdjustedShotsAttempts REAL,
    I_F_unblockedShotAttempts INTEGER,
    I_F_scoreAdjustedUnblockedShotAttempts REAL,
    I_F_dZoneGiveaways INTEGER,
    I_F_xGoalsFromxReboundsOfShots REAL,
    I_F_xGoalsFromActualReboundsOfShots REAL,
    I_F_reboundxGoals REAL,
    I_F_xGoals_with_earned_rebounds REAL,
    I_F_xGoals_with_earned_rebounds_scoreAdjusted REAL,
    I_F_xGoals_with_earned_rebounds_scoreFlurryAdjusted REAL,
    I_F_oZoneShiftStarts INTEGER,
    I_F_dZoneShiftStarts INTEGER,
    I_F_neutralZoneShiftStarts INTEGER,
    I_F_flyShiftStarts INTEGER,
    I_F_oZoneShiftEnds INTEGER,
    I_F_dZoneShiftEnds INTEGER,
    I_F_neutralZoneShiftEnds INTEGER,
    I_F_flyShiftEnds INTEGER,
    faceoffsWon INTEGER,
    faceoffsLost INTEGER,
    timeOnBench INTEGER,
    penaltyMinutes INTEGER,
    penaltyMinutesDrawn INTEGER,
    penaltiesDrawn INTEGER,
    shotsBlockedByPlayer INTEGER,
    OnIce_F_xOnGoal REAL,
    OnIce_F_xGoals REAL,
    OnIce_F_flurryAdjustedxGoals REAL,
    OnIce_F_scoreVenueAdjustedxGoals REAL,
    OnIce_F_flurryScoreVenueAdjustedxGoals REAL,
    OnIce_F_shotsOnGoal INTEGER,
    OnIce_F_missedShots INTEGER,
    OnIce_F_blockedShotAttempts INTEGER,
    OnIce_F_shotAttempts INTEGER,
    OnIce_F_goals INTEGER,
    OnIce_F_rebounds INTEGER,
    OnIce_F_reboundGoals INTEGER,
    OnIce_F_lowDangerShots INTEGER,
    OnIce_F_mediumDangerShots INTEGER,
    OnIce_F_highDangerShots INTEGER,
    OnIce_F_lowDangerxGoals REAL,
    OnIce_F_mediumDangerxGoals REAL,
    OnIce_F_highDangerxGoals REAL,
    OnIce_F_lowDangerGoals INTEGER,
    OnIce_F_mediumDangerGoals INTEGER,
    OnIce_F_highDangerGoals INTEGER,
    OnIce_F_scoreAdjustedShotsAttempts REAL,
    OnIce_F_unblockedShotAttempts INTEGER,
    OnIce_F_scoreAdjustedUnblockedShotAttempts REAL,
    OnIce_F_xGoalsFromxReboundsOfShots REAL,
    OnIce_F_xGoalsFromActualReboundsOfShots REAL,
    OnIce_F_reboundxGoals REAL,
    OnIce_F_xGoals_with_earned_rebounds REAL,
    OnIce_F_xGoals_with_earned_rebounds_scoreAdjusted REAL,
    OnIce_F_xGoals_with_earned_rebounds_scoreFlurryAdjusted REAL,
    OnIce_A_xOnGoal REAL,
    OnIce_A_xGoals REAL,
    OnIce_A_flurryAdjustedxGoals REAL,
    OnIce_A_scoreVenueAdjustedxGoals REAL,
    OnIce_A_flurryScoreVenueAdjustedxGoals REAL,
    OnIce_A_shotsOnGoal INTEGER,
    OnIce_A_missedShots INTEGER,
    OnIce_A_blockedShotAttempts INTEGER,
    OnIce_A_shotAttempts INTEGER,
    OnIce_A_goals INTEGER,
    OnIce_A_rebounds INTEGER,
    OnIce_A_reboundGoals INTEGER,
    OnIce_A_lowDangerShots INTEGER,
    OnIce_A_mediumDangerShots INTEGER,
    OnIce_A_highDangerShots INTEGER,
    OnIce_A_lowDangerxGoals REAL,
    OnIce_A_mediumDangerxGoals REAL,
    OnIce_A_highDangerxGoals REAL,
    OnIce_A_lowDangerGoals INTEGER,
    OnIce_A_mediumDangerGoals INTEGER,
    OnIce_A_highDangerGoals INTEGER,
    OnIce_A_scoreAdjustedShotsAttempts REAL,
    OnIce_A_unblockedShotAttempts INTEGER,
    OnIce_A_scoreAdjustedUnblockedShotAttempts REAL,
    OnIce_A_xGoalsFromxReboundsOfShots REAL,
    OnIce_A_xGoalsFromActualReboundsOfShots REAL,
    OnIce_A_reboundxGoals REAL,
    OnIce_A_xGoals_with_earned_rebounds REAL,
    OnIce_A_xGoals_with_earned_rebounds_scoreAdjusted REAL,
    OnIce_A_xGoals_with_earned_rebounds_scoreFlurryAdjusted REAL,
    OffIce_F_xGoals REAL,
    OffIce_A_xGoals REAL,
    OffIce_F_shotAttempts INTEGER,
    OffIce_A_shotAttempts INTEGER,
    xGoalsForAfterShifts REAL,
    xGoalsAgainstAfterShifts REAL,
    corsiForAfterShifts REAL,
    corsiAgainstAfterShifts REAL,
    fenwickForAfterShifts REAL,
    fenwickAgainstAfterShifts REAL,
    FOREIGN KEY (playerId) REFERENCES players(id),
    FOREIGN KEY (team) REFERENCES teams(code)
);

-- TODO: Goalie stats are missing the number of wins. Need to get this from NHL API instead of MoneyPuck
CREATE TABLE goalie_season_stats
(
    id INTEGER PRIMARY KEY NOT NULL,
    playerId INTEGER NOT NULL,
    season INTEGER NOT NULL,
    team CHAR(3) NOT NULL,
    situation TEXT NOT NULL CHECK (situation IN ('other', 'all', '5on5', '5on4', '4on5')),
    phase TEXT NOT NULL CHECK (phase IN ('regular', 'playoffs')),
    games_played INTEGER,
    icetime INTEGER,
    xGoals REAL,
    goals INTEGER,
    unblocked_shot_attempts INTEGER,
    xRebounds REAL,
    rebounds INTEGER,
    xFreeze REAL,
    freeze INTEGER,
    xOnGoal REAL,
    ongoal INTEGER,
    xPlayStopped REAL,
    playStopped INTEGER,
    xPlayContinuedInZone REAL,
    playContinuedInZone INTEGER,
    xPlayContinuedOutsideZone REAL,
    playContinuedOutsideZone INTEGER,
    flurryAdjustedxGoals REAL,
    lowDangerShots INTEGER,
    mediumDangerShots INTEGER,
    highDangerShots INTEGER,
    lowDangerxGoals REAL,
    mediumDangerxGoals REAL,
    highDangerxGoals REAL,
    lowDangerGoals INTEGER,
    mediumDangerGoals INTEGER,
    highDangerGoals INTEGER,
    blocked_shot_attempts INTEGER,
    penaltyMinutes INTEGER,
    penalties INTEGER,
    FOREIGN KEY (playerId) REFERENCES players(id),
    FOREIGN KEY (team) REFERENCES teams(code)
);
